# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SimpleDashboardWithTabbarRxSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SimpleDashboardWithTabbarRxSwift

  target 'SimpleDashboardWithTabbarRxSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SimpleDashboardWithTabbarRxSwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
